name: Pull request to main

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ main ]

jobs:

  EjecutaPruebas:
    name: EjecutaPruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3

    - name: Configuración de entorno de python
      uses: actions/setup-python@v3
      with:
          python-version: '3.9'

    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s test -v

    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m --omit="*/usr/lib/*" unittest discover -s test -v
          coverage report --fail-under=80
  